Adding updateCollection to jets
cmsb2g/B2GAnaFW pull request #59
Opened 2016-10-03 16:13 UTC by alefisico

- Using updateCollection from jetToolbox to use jet collections from miniAOD (slimmedJets, slimmedJetsPuppi, slimmedJetsAK8) and avoid reclustering.
- Although this PR improves a lot the framework, it needs some more work.
- This version is good for test

2016-10-03 16:25 UTC, dmajumder requested changes
@alefisico OK, so with the 'updateJetCollection' what are we adding to the jets?
- is it possible to add (unless there) the PUPPI jet substructure infos?
- B tagging should be rerun since we have a new training for the double b tagger, some bug fixes for the c tagger, and looser track requirements for b tagging in general.

2016-10-03 17:03 UTC, alefisico commented
so what exactly do you want to add? In this PR only the info that was not miniAOD is added, like trimmed/filtered jet mass. But of course I can add whatever we extra we want. Can you please give me a list of things that you want to include

2016-10-03 18:47 UTC, dmajumder commented on test/b2gedmntuples_cfg.py
> +jetToolbox( process, 'ak8', 'analysisPath', 'edmNtuplesOut', runOnMC=runMC, updateCollection=jetAK8Label, JETCorrPayload=jetAlgoAK8, addTrimming=True, rFiltTrim=0.1, addFiltering=True ) #, addSoftDro
would like to rerun the b tagging for AK8PFCHS also

2016-10-04 09:25 UTC, merged

2016-10-04 09:27 UTC, alefisico commented
@dmajumder I was about to included what you suggest, should I do it or not?

2016-10-04 10:13 UTC, dmajumder commented
@alefisico yes, you can create another PR for this.